### ISSUE TITLE
rabbitmq-common dep conflict with qdate ?

### ISSUE THREAD

**Issue by jhw** [rabbitmq/rabbitmq-common#139]
Hi,

I have an erlang.mk project which has been using amqp_client and qdate happily for a long time. On a recent 'make distclean' I am suddenly getting the following -

===> Errors generating release 
          Duplicated modules: 
    ec_semver_parser specified in erlware_commons and rabbit_common
    ec_semver specified in erlware_commons and rabbit_common

qdate pulls in erlware_commons and amqp_client pulls in rabbit_common.

@essen suggests this is a bona fide naming conflict; it looks to me the issue may have been introduced on the rabbitmq-common side. 

Is this something that could/should be fixed ?

Thank you -

**Comment by choptastic** [comment]
This is indeed a naming conflict.  As rabbitmq-common [recently copied ec_semver_* files](https://github.com/rabbitmq/rabbitmq-common/commits/master/src/ec_semver.erl) from erlware_commons rather than adding it as a dependency.

One suggestion would be to rename the copied modules to avoid the naming conflict - something like rabbit_semver and rabbit_semver_parser are (to me) the obvious choices.  Otherwise *any* project using rabbit and erlware_commons will generate these naming conflicts.

That, or just use erlware_commons as a dependency (though I understand apprehension to adding more dependencies for one or two modules).

**Comment by michaelklishin** [comment]
Renaming a module sounds like an easy way out to me.

**Comment by essen** [comment]
Also exists with mochinum and mochiweb_util. I will send a PR now.

**Comment by essen** [comment]
Should be good to review and merge.
