### ISSUE TITLE
Version 3.6.10 includes mochiweb_util modules

### ISSUE THREAD

**Issue by jlouis** [rabbitmq/rabbitmq-common#217]
Hi,

I ran into a problem with this library today. Version 3.6.10 (and supposedly also 3.6.11, but *not* 3.7.0) includes modules such as `mochinum`. This creates obvious problems when you have other dependencies who pulls in the real application/library containing these files, since release building fails (due to the same module being included twice).

What is the best way of getting rid of this?

* Option 1: Wait until 3.7.0 is released. If this is more than about 5 days in the future, I'm not going to wait, so in that case this is not an option.
* Option 2: Wait until 3.6.12. Same as above.
* Option 3: I can't use the `hex.pm` package due to the above problem, so I can roll my own version of the package with the fix from 3.7.0 backported.

I'm also somewhat perplexed that the fix is about 8 months old, but has not yet found its way into a stable production package. Is there a reason for this? And also that someone copied mochi* utils in like this without renaming them in the first place.

**Comment by michaelklishin** [comment]
hi @jlouis,

`mochinum` has been a part of RabbitMQ for a while, together with a few other Mochi projects. Some
of them were replaced since 3.6.0 for reasons other than code path conflicts. `mochinum` was [moved](https://github.com/rabbitmq/rabbitmq-common/commit/ff1ea405876386b03003b9c25159119d36e5aa89) to this library because that's where it is used.

It would help if you linked to "the fix" in question. I'm not sure why you expect 3.6.12 to be different from 3.6.11. We are really reluctant to make any more potentially breaking changes (3.6.11 includes a couple which fix issues much more significant and even then we had doubts).

3.7.0 is not too far off and you should be able to use 3.7.0 Erlang client releases against 3.6.x broker just fine (at least with network connections).

**Comment by jlouis** [comment]
Oh, you suggested the best path I think!

The solution is to bake the 3.7.0 client and use that, switching to the real source provider (`hex.pm`) once it is released. I think it'll solve the problem I have here better than trying to patch the 3.6.x world, and the client is usually not that much in flux it is likely to cause any trouble.

In any case, I'll wait it out for now and hope it solves itself in a couple of weeks. I'm not that much in a hurry anymore since I managed to push the urgency down a bit internally.
