### ISSUE TITLE
Transactions in rabbit_exchange_type callbacks

### ISSUE THREAD

**Issue by noxdafox** [rabbitmq/rabbitmq-common#263]
When looking at the `rabbit_exchange_type` behaviour, I noticed callbacks have a `transaction` parameter (which should be either `transaction` or `none`).

What is the rationale behind this and which callback shall I implement?

NOTE: the issue was edited as I figured out the original problem.

**Comment by lukebakken** [comment]
Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

Thanks!
Luke

**Comment by noxdafox** [comment]
Thanks for the guidance and sorry for the spam. I will repost the question on the mailing list.

**Comment by lukebakken** [comment]
It's no problem! We're happy to help out on `rabbitmq-users`.
